### ISSUE TITLE
Scalastyle w/Eclipse 4.6 results in exceptions in the Eclipse Error log

### ISSUE THREAD

**Issue by oharboe** [scalastyle/scalastyle-plugin#22]
To reproduce:

- Start Eclipse 4.6 w/Scalastyle-plugin 0.7
- Add Scalastyle nature to a project and enable Scalastyle
- Doubleclick on a Scala file

Exception in Error Log ensues:

`scala.reflect.internal.FatalError: ThisType(value io) for sym which is not a class
	at scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
	at scala.reflect.internal.Types$ThisType.<init>(Types.scala:1167)
	at scala.reflect.internal.Types$UniqueThisType.<init>(Types.scala:1187)
	at scala.reflect.internal.Types$ThisType$.apply(Types.scala:1191)
	at scala.tools.nsc.interactive.Global.scala$tools$nsc$interactive$Global$$findMirrorSymbol(Global.scala:875)
	at scala.tools.nsc.interactive.Global$$anonfun$getDocComment$2$$anonfun$apply$16$$anonfun$apply$18.apply(Global.scala:948)
	at scala.tools.nsc.interactive.Global$$anonfun$getDocComment$2$$anonfun$apply$16$$anonfun$apply$18.apply(Global.scala:947)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at scala.tools.nsc.interactive.Global$$anonfun$getDocComment$2$$anonfun$apply$16.apply(Global.scala:947)
	at scala.tools.nsc.interactive.Global$$anonfun$getDocComment$2$$anonfun$apply$16.apply(Global.scala:946)
	at scala.tools.nsc.interactive.Global.scala$tools$nsc$interactive$Global$$withTempUnits(Global.scala:859)
	at scala.tools.nsc.interactive.Global$$anonfun$getDocComment$2.apply(Global.scala:946)
	at scala.tools.nsc.interactive.Global$$anonfun$getDocComment$2.apply(Global.scala:946)
	at scala.tools.nsc.interactive.Global$$anonfun$respond$1.apply(Global.scala:701)
	at scala.tools.nsc.interactive.Global$$anonfun$respond$1.apply(Global.scala:701)
	at scala.tools.nsc.interactive.Global.respondGradually(Global.scala:708)
	at scala.tools.nsc.interactive.Global.respond(Global.scala:701)
	at scala.tools.nsc.interactive.Global.getDocComment(Global.scala:945)
	at scala.tools.nsc.interactive.CompilerControl$AskDocCommentItem.apply$mcV$sp(CompilerControl.scala:383)
	at scala.tools.nsc.interactive.Global$$anonfun$pollForWork$1.apply$mcV$sp(Global.scala:506)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at scala.tools.nsc.interactive.Global.pollForWork(Global.scala:431)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:22)
`

**Comment by oharboe** [comment]
Appears to be fixed in scalastyle 0.8
