### ISSUE TITLE
Exception when trying to edit a scalatyle-config.xml

### ISSUE THREAD

**Issue by oharboe** [scalastyle/scalastyle-plugin#25]
To reproduce: 

1. Select a scalastyle-config.xml from the preferences menu. Eclipse 4.6 w/Scalastyle plugin 0.8.
2. Click "Edit"
3. Exception

`
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at org.scalastyle.scalastyleplugin.preferences.ScalastyleConfigurationDialog.<init>(ScalastyleConfigurationDialog.scala:119)
	at org.scalastyle.scalastyleplugin.preferences.ScalastylePreferencePage.org$scalastyle$scalastyleplugin$preferences$ScalastylePreferencePage$$editConfiguration(ScalastylePreferencePage.scala:178)
	at org.scalastyle.scalastyleplugin.preferences.ScalastylePreferencePage$$anonfun$createContents$3.apply$mcV$sp(ScalastylePreferencePage.scala:122)
	at org.scalastyle.scalastyleplugin.SwtUtils$$anon$2.widgetSelected(SwtUtils.scala:130)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:63)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
`

**Comment by matthewfarwell** [comment]
Are you sure that the file exists?

**Comment by oharboe** [comment]
the file exists, but the project is closed.

4. mar. 2017 19:01 skrev "Matthew Farwell" <notifications@github.com>:

Are you sure that the file exists?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scalastyle/scalastyle-plugin/issues/25#issuecomment-284168941>,
or mute the thread

**Comment by matthewfarwell** [comment]
Effectively, you can't edit a config file if the project is closed. This is because Eclipse doesn't allow access to these files once the project is closed. I agree that the Exception isn't the best way to handle this, but at the end of the day there isn't much I can do.
